### ISSUE TITLE
UseCase == God Object

### ISSUE THREAD

**Issue by rhmndnt** [MrHadiSatrio/Journal3#4]
As you have stated that UseCase is a representation of business requirements/features, is it necessary that we should only have 1-to-1 mapping between Activity/Screen/Feature and UseCase?

**Comment by MrHadiSatrio** [comment]
I'd say that the answer would depend on what platform/framework you want to run this business requirements on. On Android, there's a lot you can do within just a single screen, hence running multiple `UseCase`s within, say, an activity would make sense. Whereas on another platform, it may simply be impossible (think CLI).

But I'd advise not to think in this way. Instead, think of "screens" as simply an implementation detail. Let your business (i.e., `UseCase`) dictate what it needs to get the job done. Once that is done, coerce what's left to fit to that requirement.
